version: "3.8"
services:
  mysql:
    image: mysql:5.7.31
    container_name: bc-mysql-dev
    restart: unless-stopped
    networks:
      - bc-net-dev
    volumes:
      - bc-mysql-volume-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bc-mysql-root-pass-dev
      # MYSQL_DATABASE: bc-db-dev
      # MYSQL_USER: bc-db-user-dev
      # MYSQL_PASSWORD: bc-mysql-pass-dev
    ports:
      - 3306:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    networks:
      - bc-net-dev
    volumes:
      - .:/app
    ports:
      - 4001:4001
    depends_on:
      - mysql

networks:
  bc-net-dev:
    driver: bridge
volumes:
  bc-mysql-volume-dev:
    driver: local
