version: "3.8"
services:
  mysql:
    image: mysql:5.7.31
    container_name: bc-mysql-dev
    restart: unless-stopped
    networks:
      - bc-net-dev
    volumes:
      - bc-mysql-volume-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bc-mysql-root-pass-dev
      # MYSQL_DATABASE: bc-db-dev
      # MYSQL_USER: bc-db-user-dev
      # MYSQL_PASSWORD: bc-mysql-pass-dev
    ports:
      - 3306:3306

  mysql_test:
    image: mysql:5.7.31
    container_name: bc-mysql-test
    restart: always
    networks:
      - bc-net-dev
    expose:
      - 3308
    environment:
      MYSQL_ROOT_PASSWORD: test_pass
    ports:
      - 3308:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-server
    environment:
      NODE_ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: /google_credentials.json
      DATABASE_URL: mysql://root:bc-mysql-root-pass-dev@bc-mysql-dev:3306/bc-mysql-dev
      TZ: Asia/Tokyo
    networks:
      - bc-net-dev
    volumes:
      - .:/app
      - /app/node_modules
      - ./cred.json:/google_credentials.json
    ports:
      - 4001:4001
      - 5555:5555
    depends_on:
      - mysql
      - mysql_test

networks:
  bc-net-dev:
    driver: bridge
volumes:
  bc-mysql-volume-dev:
    driver: local
