version: "3.8"
services:
  mysql:
    image: mysql:5.7.31
    container_name: bc-mysql
    restart: unless-stopped
    networks:
      - bc-net
    volumes:
      - bc-mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bc-mysql-root-pass-dev
      MYSQL_DATABASE: bc-db
      MYSQL_USER: bc-db-user-dev
      MYSQL_PASSWORD: bc-mysql-pass-dev
    ports:
      - 3306:3306

networks:
  bc-net:
    driver: bridge
volumes:
  bc-mysql-volume:
    driver: local
