version: "3.8"
services:
  mysql_test:
    image: mysql:5.7.31
    container_name: bc-mysql-test
    restart: always
    networks:
      - bc-net-dev
    expose:
      - 3308
    environment:
      MYSQL_ROOT_PASSWORD: test_pass
    ports:
      - 3308:3306

networks:
  bc-net-dev:
    driver: bridge
