name: bc-v1
on: [push]
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: docker-compose -f docker-compose.test.yml up -d bc_mysql_test
      - run: docker container exec -it bc_mysql_test bash
      - run: /etc/init.d/mysql start
      - run: yarn test
